### ISSUE TITLE
What is the difference of batch_size and batch_flush_size?

### ISSUE THREAD

**Issue by alfakini** [gzigzigzeo/sidekiq-grouping#21]
Sorry for asking this question, but it was not clear for me while reading the documentation. In the README says that:

> NOTE: As of 1.0 batch_size renamed to batch_flush_size.

But them there is this exemple that uses both:

``` ruby
class FooWorker
  include Sidekiq::Worker

  sidekiq_options batch_flush_size: 5, batch_size: 2

  def perform(n)
    puts n
  end
end
```

And them looking in the code I can see that `pluck_size` and `chunk_size` are used in different places here https://github.com/gzigzigzeo/sidekiq-grouping/blob/master/lib/sidekiq/grouping/batch.rb#L27-L35

Could someone please clarify if they are different options of are the same?

Thanks!

**Comment by bjedrocha** [comment]
They are different options. `batch_flush_size` determines the size of the queue at which point grouping will occur. `batch_size` determines the size of the group.

In your example, grouping will occur when there a 5 or more jobs in the queue but because the `batch_size` is set to 2, the number of jobs in each group will be 2. Hope this answers your question.
